name: Build-and-publish-docker-images-workflow

on:
  push:

  release:
    types: [published]

jobs:
  Build-and-publish-docker-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push All in One image
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          context: .
          push: true
          tags: fraunhoferiosb/aasportal_aio:latest

      - name: Build and push AASPortal (frontend) image
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile.aas-portal
          context: .
          push: true
          tags: fraunhoferiosb/aasportal_aasportal:latest

      - name: Build and push AASServer (backend) image
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile.aas-server
          context: .
          push: true
          tags: fraunhoferiosb/aasportal_aasserver:latest
